// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0E2vrNcsGvSv-B_cYc94kcYiCsEilyWU',
    appId: '1:975114036167:web:f4feda33e72fae4409afe2',
    messagingSenderId: '975114036167',
    projectId: 'querycode-app',
    authDomain: 'querycode-app.firebaseapp.com',
    storageBucket: 'querycode-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfgwr8SqUyvLLoyAxXMIx88MD7X-8G52g',
    appId: '1:975114036167:android:942b8d2465c26a4909afe2',
    messagingSenderId: '975114036167',
    projectId: 'querycode-app',
    storageBucket: 'querycode-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBRNvjk3fzBX94El9bmqn9B_mfAYT9VX4',
    appId: '1:975114036167:ios:290d278d00d4378509afe2',
    messagingSenderId: '975114036167',
    projectId: 'querycode-app',
    storageBucket: 'querycode-app.firebasestorage.app',
    iosBundleId: 'com.example.queryCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBRNvjk3fzBX94El9bmqn9B_mfAYT9VX4',
    appId: '1:975114036167:ios:290d278d00d4378509afe2',
    messagingSenderId: '975114036167',
    projectId: 'querycode-app',
    storageBucket: 'querycode-app.firebasestorage.app',
    iosBundleId: 'com.example.queryCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0E2vrNcsGvSv-B_cYc94kcYiCsEilyWU',
    appId: '1:975114036167:web:b970f47ee222f4d309afe2',
    messagingSenderId: '975114036167',
    projectId: 'querycode-app',
    authDomain: 'querycode-app.firebaseapp.com',
    storageBucket: 'querycode-app.firebasestorage.app',
  );
}
